import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [height, setHeight] = useState(0);
  const [heightActual, setHeightActual] = useState(0);
  useEffect(() => {
    let heightNav = 16 * 3;
    let heightDom = innerHeight;
    setHeight(heightDom - heightNav);
  }, []);

  const changeScroll = () => {
    setTimeout(() => {
      let heightNav = 16 * 3;
      let heightDom = innerHeight;
      console.log("El dom mide: " + heightDom);
      let heightAhora = heightDom - heightNav;
      let scroll = null;

      if (window.scrollY > heightActual) {
        scroll = heightActual + heightAhora;
      } else if (window.scrollY < heightActual) {
        scroll = heightActual - heightAhora;
      }

      window.scroll(0, scroll);
      setHeight(heightAhora);
      setHeightActual(scroll);
    }, 300);
  };

  return (
    <div onWheel={changeScroll} onTouchMove={changeScroll}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ background: "#456", height: height + "px" }}></div>
      <div style={{ background: "#789", height: height + "px" }}></div>
      <div style={{ background: "#abc", height: height + "px" }}></div>
      <div style={{ background: "#def", height: height + "px" }}></div>
    </div>
  );
}
