import Head from "next/head";
import { useEffect, useState } from "react";

import { colors, fonts } from "../theme";

export default function Home() {
  const [height, setHeight] = useState(0);
  const [heightActual, setHeightActual] = useState(0);
  const [slider, setSlider] = useState(0);
  useEffect(() => {
    let heightNav = 16 * 3;
    let heightDom = innerHeight;
    setHeight(heightDom - heightNav);
    let sliderActual = 0;
    setSlider(sliderActual);
  }, []);

  const changeScroll = () => {
    setTimeout(() => {
      let heightNav = 16 * 3;
      let heightDom = innerHeight;
      let heightAhora = heightDom - heightNav;

      let sliderActual = slider;

      let scroll = null;

      if (window.scrollY > heightActual) {
        sliderActual < 3
          ? (sliderActual = sliderActual + 1)
          : (sliderActual = 3);
        scroll = heightAhora * sliderActual;
        console.log(sliderActual);
      } else if (window.scrollY < heightActual) {
        sliderActual > 0
          ? (sliderActual = sliderActual - 1)
          : (sliderActual = 0);
        scroll = heightAhora * sliderActual;
        console.log(sliderActual);
      }

      window.scroll(0, scroll);

      setHeight(heightAhora);
      setHeightActual(scroll);
      setSlider(sliderActual);
    }, 800);
  };

  return (
    <div onWheel={changeScroll} onTouchMove={changeScroll}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="slider-1" style={{ height: height + "px" }}>
        <h1>
          ULTRA
          <br />
          BODEGON
        </h1>
      </div>
      <div className="slider-2" style={{ height: height + "px" }}>
        <h2>Trabajamos</h2>
        <p>para un bien mayor en nuestras comunidades</p>
        <h2>Nos hacemos cargo</h2>
        <p>de llevar el sustento a todos los venezolanos</p>
        <h2>Somos receptivos</h2>
        <p>a las necesidades básicas de los venezolanos</p>
      </div>
      <div
        style={{
          background: "#789",
          height: height + "px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <h1>Es</h1>
      </div>
      <div
        style={{
          background: "#def",
          height: height + "px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <h1>Prueba</h1>
      </div>
      <style jsx>{`
        .slider-1 {
          align-items: center;
          background: #444;
          color: #fff;
          display: flex;
          justify-content: center;
        }

        .slider-1 > h1 {
          font-size: 3rem;
          text-align: center;
        }

        .slider-2 {
          align-items: center;
          display: flex;
          flex-direction: column;
          justify-content: center;
          text-align: center;
          padding: 0 5%;
        }
      `}</style>
    </div>
  );
}
