import { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";

import Producto from "../components/general/producto";
import SliderH from "../components/index/slider";

export default function Home() {
  const [height, setHeight] = useState(0);
  const [width, setWidth] = useState(0);
  const [heightActual, setHeightActual] = useState(0);
  const [slider, setSlider] = useState(0);

  useEffect(() => {
    let heightNav = 16 * 3;
    let heightDom = innerHeight;
    setHeight(heightDom - heightNav);
    let sliderActual = 0;
    setSlider(sliderActual);
    setWidth(innerWidth);
  }, []);

  const changeScroll = () => {
    setTimeout(
      () => {
        let heightNav = 16 * 3;
        let heightDom = innerHeight;
        let heightAhora = heightDom - heightNav;

        let sliderActual = slider;

        let scroll = null;

        if (window.scrollY > heightActual) {
          sliderActual < 1
            ? (sliderActual = sliderActual + 1)
            : (sliderActual = 1);
          scroll = heightAhora * sliderActual;
        } else if (window.scrollY < heightActual) {
          sliderActual > 0
            ? (sliderActual = sliderActual - 1)
            : (sliderActual = 0);
          scroll = heightAhora * sliderActual;
        }

        window.scroll(0, scroll);

        setHeight(heightAhora);
        setWidth(innerWidth);
        setHeightActual(scroll);
        setSlider(sliderActual);
      },
      width < 500 ? 800 : 400
    );
  };

  const scrollMovil = () => {
    let heightNav = 16 * 3;
    let heightDom = innerHeight;
    let heightAhora = heightDom - heightNav;

    let sliderActual = slider;

    let scroll = null;

    if (window.scrollY > heightActual) {
      sliderActual < 1 ? (sliderActual = sliderActual + 1) : (sliderActual = 1);
      scroll = heightAhora * sliderActual;
    } else if (window.scrollY < heightActual) {
      sliderActual > 0 ? (sliderActual = sliderActual - 1) : (sliderActual = 0);
      scroll = heightAhora * sliderActual;
    }

    window.scroll(0, scroll);

    setTimeout(() => window.scroll(0, scroll), 500);

    setHeight(heightAhora);
    setWidth(innerWidth);
    setHeightActual(scroll);
    setSlider(sliderActual);
  };

  return (
    <div style={{ width: width + "px" }} onWheel={changeScroll}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        onTouchEnd={scrollMovil}
        className="slider-1"
        style={{ height: height + "px" }}
      >
        <div className="slider-1__principal">
          <h1>
            ULTRA
            <br />
            BODEGON
          </h1>
        </div>
      </div>
      <div
        style={{
          width: "100%",
          height: height + "px",
        }}
      >
        <SliderH height={height} width={width} scrollArriba={scrollMovil} />
      </div>
      <div style={{ height: height / 2 + "px" }}></div>
      <style jsx>{`
        .slider-1 {
          background: #333;
          color: #fff;
          display: grid;
          grid-template-areas: "principal" "contacto";
          grid-template-columns: 1fr;
          grid-template-rows: auto 3rem;
        }

        .slider-1__principal {
          align-items: center;
          display: flex;
          justify-content: center;
          text-align: center;
        }

        .slider-1 > h1 {
          font-size: 2.5rem;
          text-align: center;
        }

        .slider-3 {
          align-items: center;
          display: flex;
          justify-content: center;
        }
      `}</style>
    </div>
  );
}
